[package]
name = "signal-provisioning-api"
version = "0.1.0"
authors = ["Tomas Drtina <tm.drtina@gmail.com>"]
edition = "2018"

[dependencies]
libsignal-protocol = { git = "https://github.com/signalapp/libsignal-client.git", tag = "v0.8.4" }
signal-crypto = { git = "https://github.com/signalapp/libsignal-client.git", tag = "v0.8.4" }

aes = "0.7.4"
subtle = "2.3"
block-modes = "0.8"

base64 = "0.13.0"
bytes = "^1"
prost = "0.8"
rand = "0.7.3"

[build-dependencies]
prost-build = "0.8"
